### ISSUE TITLE
Two flapjackfeeders doesn't work

### ISSUE THREAD

**Issue by jessereynolds** [flapjack/flapjackfeeder#11]
If you try and configure two flapjackfeeder brokers in your Nagios, only the first of them will actually transmit events on to Flapjack, however both will establish their own TCP sockets to redis. 

I also tried changing the NEBMODULE_MODINFO_TITLE to "flapjackfeeder-staging" and compiling it to "flapjackfeeder-staging.o" but this makes no difference. 

Perhaps there's some global variables that are in scope in both instances of the module, or something.

**Comment by jessereynolds** [comment]
Example config:

```
broker_module=/usr/local/lib/flapjackfeeder.o redis_host=flapjack.example,redis_port=6380
broker_module=/usr/local/lib/flapjackfeeder-staging.o redis_host=flapjack-staging.example,redis_port=6380
```

**Comment by bs-github** [comment]
I've tested quite a lot and came up with a version where I changed all the names.
That worked, but is less that optimal and therefore I reverted that right away.
See here: https://github.com/flapjack/flapjackfeeder/commit/5dfa82a3e0da6ee035a3b2baae399cf55248603d

The better way to go would surely be to modify the code to support multiple targets.

**Comment by jessereynolds** [comment]
Makes sense @bs-github 

We need to take care we're not introducing latency into Nagios's check execution by adding a second redis endpoint for flapjackfeeder.

**Comment by bs-github** [comment]
pending merge: https://github.com/flapjack/flapjackfeeder/pull/12
