### ISSUE TITLE
flapjackfeeder no longer works against naemon 1.0.4

### ISSUE THREAD

**Issue by elmobp** [flapjack/flapjackfeeder#18]
[1466853358] Error: Could not load module '/usr/local/lib/flapjackfeeder4.o' -> /usr/local/lib/flapjackfeeder4.o: undefined symbol: schedule_new_event
[1466853358] Error: Failed to load module '/usr/local/lib/flapjackfeeder4.o'.

Looks like to moved to schedule_event

**Comment by bs-github** [comment]
I'll have a look at this...

**Comment by bs-github** [comment]
Here is the commit message that seems to bring some light to the issue: https://github.com/naemon/naemon-core/commit/b0d21993e24388fd0ad6a1aa39989895406b93bd
I'll probably alter the module to use `schedule_event` instead of `schedule_new_event` surrounded by some ifdefs.

**Comment by bs-github** [comment]
working branch is https://github.com/flapjack/flapjackfeeder/tree/naemon-1.0.5

**Comment by bs-github** [comment]
but as of now it breaks builds for older versions :-(
