### ISSUE TITLE
support Naemon and Nagios 4

### ISSUE THREAD

**Issue by jessereynolds** [flapjack/flapjackfeeder#7]

**Comment by alivespirit** [comment]
Hi,
Are there any plans on this? Currently trying to run Nagios 4.0.3 with specified broker_module fails with
```
Error: Module '/usr/local/lib/flapjackfeeder.o' is using an old or unspecified version of the event broker API.  Module will be unloaded.
```

**Comment by bs-github** [comment]
Sorry, I've had this working for quite a while. But only commited yesterday.
https://github.com/flapjack/flapjackfeeder/commit/ea0b040d09b3322cb25e5f76ee17d24ec6e65a73

**Comment by alivespirit** [comment]
What are the prerequisites to build module? I'm trying to compile it on vagrant-flapjack machine, but without luck. Or can you please send me compiled module with Nagios 4 support?

Thanks,
Roman

**Comment by bs-github** [comment]
Hi Roman,
I've updated the README on how to build the Nagios4 version of the module. 
Hope that helps.
Cheers,
Birger

**Comment by bs-github** [comment]
even more simple now, see https://github.com/flapjack/flapjackfeeder/issues/9
