### ISSUE TITLE
tagging checks

### ISSUE THREAD

**Issue by pulecp** [flapjack/flapjackfeeder#8]
#question
We are just trying to deploy flapjack with Icinga.

We would need to tagging checks going from Icinga to flapjack or add some special field from Icinga like "servicegroups" or " membership" of host/service. We would like to use tagging as in Sensu, where you can define for every check any tags.

I found definition of NEB module which Flapjackfeeder is using http://larsmichelsen.com/nagios/nagios-event-broker/. There is noted that full list of information which we can get from Icinga through this module can be found in the nebcallbacks.h https://github.com/Icinga/Icinga-core/blob/master/include/nebcallbacks.h. But I'm not sure if is possible to get above mentioned information about check. If it would be possible then we could adjust Flapjackfeeder to sending relevant data to the Flapjack where we can parse it.

**Comment by jessereynolds** [comment]
@bs-github is now working on this. The plan is to pick up the following custom variables from the Nagios/Naemon/Icinga configuration:

- `_tags` - containing tags delimited by `!`
- `_initial_failure_delay` - in seconds
- `_repeat_failure_delay` - in seconds

**Comment by bs-github** [comment]
The code is still not 100%, but a good part of it should be done.
https://github.com/flapjack/flapjackfeeder/commit/2699b49f39552d47750ead7c794e9dfafd9c1212

One thing is implemented differently:
For `_tags` - containing tags delimited by `!` the code ignores the `!`s completely.
But you can use multiple `_tags` lines instead.

**Comment by jessereynolds** [comment]
Excellent work. 

With _tags - do you mean that Nagios doesn't send through the full value including the `!`s? Or that you haven't done the split yet?

**Comment by bs-github** [comment]
I haven't done a split on `!` and I do even think multiple `_tags` lines are more elegant.
Also that already works.
So, I tend to not implement the split thing.

**Comment by jessereynolds** [comment]
OK. Perhaps we should change it to `_tag`  (singular) then.

**Comment by bs-github** [comment]
done.
