### ISSUE TITLE
Employ make or other appropriate build tool

### ISSUE THREAD

**Issue by jessereynolds** [flapjack/flapjackfeeder#9]
So we can build by just running 'make'. I'm not sure how best to handle downloading of the redis library and any other dependencies.

We can also then have travis automatically building flapjackfeeder and telling us about any compilation errors.

We might even like to add some tests :-)

**Comment by jessereynolds** [comment]
Travis recommend using 
- biicode for dependency management
- autotools and make for the building

http://docs.travis-ci.com/user/languages/c/

**Comment by bs-github** [comment]
see pull request https://github.com/flapjack/flapjackfeeder/pull/13
Maybe having a git submodule would be better than cloning the hiredis git repo from the Makefile, but it works how it's done now.
https://github.com/flapjack/flapjackfeeder/blob/ecaaf4f4200783d9304ddcdde6d3027475fbc7fe/Makefile#L31-L34

**Comment by SarahKowalik** [comment]
I'm fine with cloning it - we're already doing this in omnibus-flapjack.

**Comment by bs-github** [comment]
merged.
